server{
    listen: 80

    # /apiへのhttpリクエストはこっちに流す
    location /api {
        proxy_pass http://localhost:8080/api;
    }

    # それ以外はこっちに流す
    location / {
        root    /var/www;
        index   index.html index.htm;
    }
}